### ISSUE TITLE
SCT instead of log transformed

### ISSUE THREAD

**Issue by bmanzato** [prabhakarlab/Banksy#22]
Hi,

I'm using Banksy with the multisample vignette. I see that to create the SpatialExperiment object, the raw count and log transformed matrices are required. We have the raw and SCT transformed data, does Banksy support using SCT instead of log-transformed?

**Comment by jleechung** [comment]
Hi @bmanzato, BANKSY should in-principle work with sctransformed data, since the spatial feature augmentation strategy BANKSY uses is agnostic to normalisation method.

Supplying the name of the SCT assay to the `assay_name` argument of `computeBanksy` should compute BANKSY matrices based on the sctransformed data. 

In addition, based on [this Seurat vignette](https://satijalab.org/seurat/articles/sctransform_vignette.html), you may not want to perform feature-wise scaling on the sctransformed data before PCA. I've just pushed a [commit](https://github.com/prabhakarlab/Banksy/commit/a469e9dadb33b858986953a795839c244d7af4ff) that allows for this. Re-install the latest version (0.99.9) from GitHub. When running PCA on the BANKSY matrix, simply add `scale = FALSE`, e.g.:
```
spe_joint <- runBanksyPCA(spe_joint, use_agf = use_agf, lambda = lambda, scale = FALSE, seed = 1000)
```

In case you find that batch effects are present due to removal of scaling, you may want to try using the [BANKSY-Harmony](https://prabhakarlab.github.io/Banksy/articles/batch-correction.html) pipeline with SCT data.
