### ISSUE TITLE
After loading the Banksy package, an error occurs when trying to create an object using BanksyObject.

### ISSUE THREAD

**Issue by yuanjiao123** [prabhakarlab/Banksy#24]
![屏幕截图 2024-04-01 205510](https://github.com/prabhakarlab/Banksy/assets/160508212/ac088a16-6694-4dd5-beb6-b3e5fb7a88e9)

> # ------ start clustering block ---------
  bank <- BanksyObject(own.expr = expr.list, cell.locs = locs.list)
Error in BanksyObject(own.expr = expr.list, cell.locs = locs.list) : 
  could not find function "BanksyObject"

**Comment by jleechung** [comment]
Hi @yuanjiao123, which version of BANKSY are you using? You can check with `packageVersion('Banksy')`. 

If you want to use the `BanksyObject` class, you'll have to install the `0.1.z` version. You can do so with:
```
remotes::install_github('prabhakarlab/Banksy@main')
```

The latest version of BANKSY uses `SingleCellExperiment` or `SpatialExperiment` objects instead of `BanksyObject` for compatibility with Bioconductor workflows. You can install this with:
```
remotes::install_github('prabhakarlab/Banksy')
```
with accompanying vignettes [here](https://prabhakarlab.github.io/Banksy/).

**Comment by yuanjiao123** [comment]
Thank you very much, the issue has been resolved

**Comment by yuanjiao123** [comment]
Thank you very much, the issue has been resolved.@jleechung
