### ISSUE TITLE
choose the right k_geom parameter

### ISSUE THREAD

**Issue by rocketeer1998** [prabhakarlab/Banksy#35]
Hi @yhtgrace @vipulsinghal02 @leranlily @jinyueliu0 @reemabaskar , thanks for your contribution to this great tool! I wonder whether I can set `k_geom <- 30` regardless of platform where platforms can be divided into NGS-based ST and Imaging-based ST?

**Comment by vipulsinghal02** [comment]
Hi @rocketeer1998, yes sure, in general, k_geom = 30 should work fine, though the default is 15, that that is what we recommend. We find results in general are quite robust to moderate variations in this parameter. A few pointers:

- If the spatial feautres you are looking for in your data are small, you might want to try smaller values. 
- If you are using Visium v1/v2 (55um hexagonal spots), then k_geom = 18 is better, since this corresponds to taking two full concentric rings around the index cell. 
- If you are using other technologies, we recommend k_geom = 15 for most technologies if `compute_agf = FALSE` and `use_agf = FALSE` (see vignettes), and k_geom = c(15, 30) if you set the agf flags to true (this uses 15 for the mean and 30 for the AGF).

**Comment by rocketeer1998** [comment]
Clear explanation, thanks!
